### ISSUE TITLE
Can't run the code

### ISSUE THREAD

**Issue by IlhamSambudi** [RaflyLesmana3003/instagram-scaper#1]
I cant run my current project using python

**Comment by RaflyLesmana3003** [comment]
you can to this step

## Installation ⚙️

1. Fork/Clone/Download this repo

    `git clone https://github.com/RaflyLesmana3003/instagram-scaper`

2. Navigate to the directory

    `cd Osintgram`

3. Create a virtual environment for this project

    `python3 -m venv venv`

4. Load the virtual environment
   - On Windows Powershell: `.\venv\Scripts\activate.ps1`
   - On Linux and Git Bash: `source venv/bin/activate`
  
5. Run `pip install -r requirements.txt`

6. Open the `credentials.ini` file in the `config` folder and write your Instagram account username and password in the corresponding fields
    
    Alternatively, you can run the `make setup` command to populate this file for you.

7. Run the main.py script in one of two ways
    * make sure your venv is activate (Linux and Git Bash : `source venv/bin/activate` or Windows  `.\venv\Scripts\activate.ps1`)
    * As an interactive prompt `python3 main.py <target instagram username>`
    * Or execute your command straight away `python3 main.py <target username> --command <command>`
